### ISSUE TITLE
H13 Error under load

### ISSUE THREAD

**Issue by nimrod-codota** [emk/rust-buildpack-example-rocket#3]
Hey,

While trying to use this buildpack to run our app @ heroku I have encountered a situation where we are getting H13 errors from heroku under load. This might be a Rocket issue, though the exact same code is doing well when hosted elsewhere, so it looks like some integration issue. I've implemented a counting `Fairing` and it doesn't even receive these requests, they seem to be failing at the network level and not reaching our app. This is what the log says:

```<app_name> heroku/router at=error code=H13 desc="Connection closed without response" method=POST path="<different pathes>" host=<app_name> request_id=xxx fwd="xxx" dyno=web.1 connect=0ms service=0ms status=503 bytes=561 protocol=http tls_version=unknown```

Would be happy to investigate further, appreciate your advise as for what I should try

Thanks a lot in advance!

Nimrod

**Comment by emk** [comment]
Unfortunately, I have no idea what might cause this.. You might try updating the example to the latest release of Rocket, and if it still fails, contacting the Rocket project. Good luck, and I wish I could do more to help.

**Comment by nimrod-codota** [comment]
Fixed by setting keep-alive to 0 as recommended by the Rocket maintainers when facing this issue. See https://github.com/emk/rust-buildpack-example-rocket/pull/4
